### ISSUE TITLE
[GLPI 9.4.4] Search doesn't work

### ISSUE THREAD

**Issue by robsonjorgefernandez** [fusioninventory/fusioninventory-for-glpi#2869] opened 2019-09-27 19:30 UTC
When I try to filter a computer in **Assets** > **Computers** the same doesn't work.
If I disable the plugin **FusionInventory** the filter works!

Plugin FusionInventory enable:
![search01](https://user-images.githubusercontent.com/16673533/65796480-14d3e400-e143-11e9-8a21-09e8c3f4e453.png)

Looking for **Dell**:
![search02](https://user-images.githubusercontent.com/16673533/65796479-13a2b700-e143-11e9-97d6-e60b4227ff30.png)

Error log:
<pre>
[2019-09-27 16:16:07] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/glpi-9.4.4/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, 'usuario' AS currentuser,
                        `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_Computer_1`,
                        `glpi_computers`.`id` AS `ITEM_Computer_1_id`,
                        `glpi_entities`.`completename` AS `ITEM_Computer_80`,  `glpi_locations`.`completename` AS `ITEM_Computer_3`,  `glpi_computers`.`contact` AS `ITEM_Computer_7`,  `glpi_manufacturers`.`name` AS `ITEM_Computer_23`,  `glpi_states`.`completename` AS `ITEM_Computer_31`,  `glpi_computers`.`serial` AS `ITEM_Computer_5`,  `glpi_computertypes`.`name` AS `ITEM_Computer_4`,  `glpi_computermodels`.`name` AS `ITEM_Computer_40`,  `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_45`,  `glpi_operatingsystemversions_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_46`,  `glpi_computers`.`date_mod` AS `ITEM_Computer_19`,  `glpi_plugin_fusioninventory_inventorycomputercomputers_id`.`last_fusioninventory_update` AS `ITEM_Computer_5150` FROM `glpi_computers`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_computers`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_states` 
                                          ON (`glpi_computers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_computertypes` 
                                          ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id`
                                              )LEFT JOIN `glpi_computermodels` 
                                          ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id`
                                              ) LEFT JOIN `glpi_items_operatingsystems` 
                                          ON (`glpi_computers`.`id` = `glpi_items_operatingsystems`.`items_id`
                                              AND `glpi_items_operatingsystems`.`itemtype` = 'Computer'
                                              ) LEFT JOIN `glpi_operatingsystems`  AS `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`
                                          ON (`glpi_items_operatingsystems`.`operatingsystems_id` = `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`id`
                                              )LEFT JOIN `glpi_operatingsystemversions`  AS `glpi_operatingsystemversions_9719987b154aaf3b42c3db32aef59090`
                                          ON (`glpi_items_operatingsystems`.`operatingsystemversions_id` = `glpi_operatingsystemversions_9719987b154aaf3b42c3db32aef59090`.`id`
                                              ) LEFT JOIN `glpi_plugin_fusioninventory_inventorycomputercomputers`
                    AS glpi_plugin_fusioninventory_inventorycomputercomputers_id
                    ON (`glpi_computers`.`id` = `glpi_plugin_fusioninventory_inventorycomputercomputers_id`.`computers_id` )  WHERE  `glpi_computers`.`is_deleted` = 0  AND `glpi_computers`.`is_template` = 0  AND (  (   (`glpi_computers`.`name`  LIKE '%dell%'  )  OR  (`glpi_entities`.`completename`  LIKE '%dell%'  )  OR  (`glpi_locations`.`completename`  LIKE '%dell%'  )  OR  (`glpi_computers`.`contact`  LIKE '%dell%'  )  OR  (`glpi_manufacturers`.`name`  LIKE '%dell%'  )  OR  (`glpi_states`.`completename`  LIKE '%dell%'  )  OR  (`glpi_computers`.`serial`  LIKE '%dell%'  )  OR  (`glpi_computertypes`.`name`  LIKE '%dell%'  )  OR  (`glpi_computermodels`.`name`  LIKE '%dell%'  )  OR  (`glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name`  LIKE '%dell%'  )  OR  (`glpi_operatingsystemversions_9719987b154aaf3b42c3db32aef59090`.`name`  LIKE '%dell%'  )  OR  (CONVERT(`glpi_computers`.`date_mod` USING utf8)  LIKE '%dell%'  )  OR  (CONVERT(`glpi_plugin_fusioninventory_inventorycomputercomputers`.`last_fusioninventory_update` USING utf8)  LIKE '%dell%'  ))  ) ORDER BY ITEM_Computer_1 ASC 
  Error: Unknown column 'glpi_plugin_fusioninventory_inventorycomputercomputers.last_fusioninventory_update' in 'where clause'
  Backtrace :
  inc/search.class.php:1246                          
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  front/computer.php:39                              Search::show()
  {"user":"13@php01"} 
</pre>

Now if I disable the plugin FusionInventory:
![search03](https://user-images.githubusercontent.com/16673533/65796651-8b70e180-e143-11e9-965e-40a4312039ea.png)

<details><summary>GLPI setup</summary>
<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.4",
        "plugins": [
            {
                "key": "formcreator",
                "version": "2.8.5"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.18-MariaDB-log",
            "size": "6304.5",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.30",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "20M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.7 (Maipo)",
            "version": "3.10.0-1062.el7.x86_64"
        }
    }
}
</pre>
</details>

**Comment by Nazghub** [comment] 2019-09-27 21:12
Hi, we are suffering the same issue here after a GLPI migration from 9.4.2 to 9.4.4.
FusionInventory was already up to date (9.4+1.1).
Enabling FI prevents searching, disabling FI let us find back our devices.
Using GLPI 9.4.4 + MySQL 8.0.17 + w2012R2/IIS/PHP 7.3.9
Merci pour votre aide :)

**Comment by TheRich-71** [comment] 2019-10-16 10:58
Hi, I have a similar error, but caused by the cronjob glpi/front/cron.php, so spamming my mailbox every few minutes. I did not yet check if it occurs by searching as well...

I attach the error mail for your reference...
[Error caused by cronjob.txt](https://github.com/fusioninventory/fusioninventory-for-glpi/files/3733891/Error.caused.by.cronjob.txt)

**Comment by ddurieux** [comment] 2019-11-29 11:53
PR merged

**Closed** 2019-11-29 11:53 UTC
