### ISSUE TITLE
9.2+1.0-9.3+1.1: Display/Usability Issue: "Tasks - Monitoring/Logs" empty

### ISSUE THREAD

**Issue by finalbeta** [fusioninventory/fusioninventory-for-glpi#2600] opened 2018-07-18 12:21 UTC
After upgrading to GLPI 9.3.0 and FusionInventory 9.3+1.1

Existing and new tasks are no longer displayed under "Tasks - Monitoring/Logs" in the Fusioninventory interface. 
The tasks status can still be tracked under the task itself under "Task management - taskname - Job executions"

No errors can be found in the PHP errors log and I can't find any info on the issue in glpi logs. 
I can provide more logs if requested.

**Comment by doudz** [comment] 2018-07-18 15:04
Same issue for me, since 9.3+1.0

**Comment by tabad** [comment] 2018-07-18 16:13
Hello @finalbeta,

This issue happens in FI4G v9.2+1.0 too. It's an *old* problem.

**Comment by finalbeta** [comment] 2018-07-18 20:39
Hi @tabad, I changed the title to reflect this. Are you just posting to confirm (does an older bugreport exist? Do you happen to have any more information about the issue from your experience?)

**Comment by tabad** [comment] 2018-07-19 07:00
Hello @finalbeta,

I looked for a previous issue with this theme but I didn't found it. I have been able this morning. The issue is #2341 (see this [comment](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2341#issuecomment-388117773)).

Regards,

**Comment by Darkellin** [comment] 2018-09-13 15:16
I have same problem to. Debian 9.5(x64),  Apache/2.4.25 (Debian), PHP 7.0.30, perl 5.24.1, GLPI 9.3, Fusioninventory plugin 9.3+1.1.

**Comment by alessiotomelleri** [comment] 2018-09-17 07:52
Same problem here...

CentOS Linux release 7.5.1804
GLPI 9.3.1  (problem just appeared in glpi 9.3.0 )
Fusioninventory 1.1

 
but table is populate :
From mysql:
#mysql -u root -p
#mysql> SELECT * FROM glpi_plugin_fusioninventory_taskjoblogs;
...
166 rows in set (0.00 sec)

Regards

**Comment by ddurieux** [comment] 2018-09-17 11:58
Is the table glpi_plugin_fusioninventory_taskjoblogs need to be repaired?

**Comment by alessiotomelleri** [comment] 2018-09-17 12:10
> Is the table glpi_plugin_fusioninventory_taskjoblogs need to be repaired?

@ddurieux  if are you asking me... table seems ok to me, no evidence about corrupt... is there some way/test to check what you ask ?!

**Comment by ddurieux** [comment] 2018-09-17 12:16
ok.
How do you have installed the plugin FusionInventory? uncompress under old folder or uncompress in new empty folder?

**Comment by alessiotomelleri** [comment] 2018-09-17 12:18
if I remember well... renamed old and as root, uncompressed it in plugins...

**Comment by ppenin** [comment] 2018-09-17 12:31
Php errors,  yes  every 5 seconds :

2018-09-17 14:19:33 [4519@s001linux02]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:440                          Toolbox::deprecated()
  inc/db.function.php:238                            DbUtils->getAllDataFromTable()
  plugins/fusioninventory/inc/timeslot.class.php:189 getAllDatasFromTable()
  plugins/fusioninventory/inc/task.class.php:344     PluginFusioninventoryTimeslot->getTimeslotEntries()
  ...fusioninventory/inc/communication.class.php:270 PluginFusioninventoryTask->getTaskjobstatesForAgent()
  ...fusioninventory/inc/communication.class.php:472 PluginFusioninventoryCommunication->getTaskAgent()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()

SQL errors : only when a new OS is updated and an OS is already defined

[2018-09-17 13:08:34] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_operatingsystems` (`items_id`, `itemtype`, `operatingsystems_id`, `operatingsystemversions_id`, `operatingsystemservicepacks_id`, `operatingsystemarchitectures_id`, `license_number`, `license_id`, `is_dynamic`, `entities_id`, `is_recursive`, `date_creation`, `date_mod`) VALUES ('260', 'Computer', '1', '5', '3', '0', 'FMWKH-WP3QC-3JH98-J8BX2-2QJMB', '82503-OEM-0621203-00032', '1', '5', '0', '2018-09-17 13:08:33', '2018-09-17 13:08:33')
  Error: Duplicate entry '260-Computer-1-0' for key 'unicity'
  Backtrace :
  inc/dbmysql.class.php:921
  inc/commondbtm.class.php:621                       DBmysql->insert()
  inc/commondbtm.class.php:1067                      CommonDBTM->addToDB()
  plugins/ocsinventoryng/inc/os.class.php:258        CommonDBTM->add()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1228 PluginOcsinventoryngOS::updateComputerOS()
  plugins/ocsinventoryng/front/ocsng.sync.php:52     PluginOcsinventoryngOcsProcess::synchronizeComputer()
  {"user":"8@s001linux02","mem_usage":"0.187\", 5.74Mio)"}

**Comment by alessiotomelleri** [comment] 2018-09-17 12:33
@ppenin  mine as well...
@ddurieux I checked my history and confirm that steps
- renamed old
- uncompressed the new in plugins
- move old elsewhere as backup

in php_error.log these last line...

2018-09-17 11:05:17 [12@mydomain]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:377                          Toolbox::deprecated()
  inc/db.function.php:205                            DbUtils->countElementsInTableForMyEntities()
  plugins/fusioninventory/inc/menu.class.php:804     countElementsInTableForMyEntities()
  plugins/fusioninventory/front/menu.php:56          PluginFusioninventoryMenu::board()
2018-09-17 11:05:42 [12@mydomain]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:377                          Toolbox::deprecated()
  inc/db.function.php:205                            DbUtils->countElementsInTableForMyEntities()
  plugins/fusioninventory/inc/menu.class.php:804     countElementsInTableForMyEntities()
  plugins/fusioninventory/front/menu.php:56          PluginFusioninventoryMenu::board()
2018-09-17 12:28:54 [12@mydomain]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:377                          Toolbox::deprecated()
  inc/db.function.php:205                            DbUtils->countElementsInTableForMyEntities()
  plugins/fusioninventory/inc/menu.class.php:804     countElementsInTableForMyEntities()
  plugins/fusioninventory/front/menu.php:56          PluginFusioninventoryMenu::board()

**Comment by ddurieux** [comment] 2018-09-17 12:35
It's deprecated, so only warning. 
I have no more idea :(

**Comment by alessiotomelleri** [comment] 2018-09-17 12:52
@ddurieux  above you asked for  "glpi/files/_log/" but I don't ha this folder in /usr/share/glpi ?!
And in /var/log  only glpi/  and  mariadb/  (related to the issue)

**Comment by Wolvverine** [comment] 2018-09-25 13:08
Maybe because it does not perform this query, look in the debug mode on the sql queries on this page.

**Comment by alessiotomelleri** [comment] 2018-09-26 07:06
Hi, below is what I get... when I click monitor/log in debug

What let me odd is last query is searching for id=46 ?!   but maybe I'm wrong something ?!

`

N° | Queries | Time | Errors
-- | -- | -- | --
1 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winupdates%' | 0.003 |  
2 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_proxysettings%' | 0.003 |  
3 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winusers%' | 0.003 |  
4 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_teamviewers%' | 0.003 |  
5 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_osinstalls%' | 0.003 |  
6 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_networkshares%' | 0.003 |  
7 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE  `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND  `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_runningprocesses%' | 0.003 |  
8 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_services%' | 0.003 |  
9 | SELECT * FROM `glpi_configs` WHERE `context` = 'browsernotification' | 0.001 |  
10 | SELECT * FROM `glpi_configs` WHERE `context` = 'browsernotification (12)' | 0.000 |  
11 | SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
12 | SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '39' LIMIT 1 | 0.000 |  
13 | SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
14 | SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '39' LIMIT 1 | 0.000 |  
15 | SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_fusioninventory_configs%' | 0.003 |  
16 | SELECT * FROM `glpi_plugin_fusioninventory_configs` | 0.001 |  
17 | SELECT `agent_base_url` FROM `glpi_plugin_fusioninventory_entities`          WHERE `entities_id`='0'             AND `agent_base_url` IS NOT NULL             AND `agent_base_url` != ''          LIMIT 1 | 0.001 |  
18 | SELECT  `id` FROM `glpi_crontasks` WHERE `glpi_crontasks`.`name` = 'taskscheduler' AND `glpi_crontasks`.`itemtype` = 'PluginFusioninventoryTask' | 0.000 |  
19 | SELECT * FROM `glpi_crontasks` WHERE `glpi_crontasks`.`id` = '46' LIMIT 1 | 0.000

`

**Comment by criensmm** [comment] 2018-10-17 09:01
Hi,
same probleme here, GLPI 9.2.4 + Fusion 9.2+2.1


SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'manufacturersimports' | 0.000 |  
-- | -- | --
2 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
3 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
4 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpidb' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_fusioninventory_configs%' | 0.002 |  
5 | SELECT * FROM `glpi_plugin_fusioninventory_configs` | 0.000 |  
6 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'formcreator' | 0.000 |  
7 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'formcreator' | 0.000 |  
8 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpidb' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_formcreator_forms%' | 0.002 |  
9 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpidb' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_formcreator_forms_profiles%' | 0.002 |  
10 | SELECT COUNT(glpi_plugin_formcreator_forms.id) FROM glpi_plugin_formcreator_forms WHERE glpi_plugin_formcreator_forms.`is_active` = 1 AND glpi_plugin_formcreator_forms.`is_deleted` = 0 AND (glpi_plugin_formcreator_forms.`language` = 'fr_FR' OR glpi_plugin_formcreator_forms.`language` IN ('0', '', NULL)) AND ( 1 ) AND (glpi_plugin_formcreator_forms.`access_rights` != 2 OR glpi_plugin_formcreator_forms.`id` IN ( SELECT plugin_formcreator_forms_id FROM glpi_plugin_formcreator_forms_profiles WHERE profiles_id = 4)) | 0.000 |  
11 | SELECT * FROM `glpi_plugins` WHERE `state` = 1 | 0.000 |  
12 | SELECT `agent_base_url` FROM `glpi_plugin_fusioninventory_entities` WHERE `entities_id`='0' AND `agent_base_url` IS NOT NULL AND `agent_base_url` != '' LIMIT 1 | 0.000 |  
13 | SELECT `glpi_crontasks`.* FROM `glpi_crontasks` WHERE `glpi_crontasks`.`name` = 'taskscheduler' AND `glpi_crontasks`.`itemtype` = 'PluginFusioninventoryTask'

**Comment by GitStorm** [comment] 2018-11-02 10:33
Same/similar problem here with GLPI 9.3.2 / FusionInventory 9.3+1.0.
CentOS Linux release 7.5.1804 (Core)
MariaDB Server 10.3.10-MariaDB
Apache/2.4.6 (CentOS)
PHP 7.2.6

**Task Job Logs table is empty:**
```
MariaDB [glpi]> SELECT * FROM glpi_plugin_fusioninventory_taskjoblogs;
Empty set (0.000 sec)
```

**Debug info from UI:**

N° | Queries | Time | Errors
-- | -- | -- | --
1 | SELECT `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
2 | SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '1' LIMIT 1 | 0.000 |  
3 | SELECT `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
4 | SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '1' LIMIT 1 | 0.000 |  
5 | SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_fusioninventory_configs%' | 0.001 |  
6 | SELECT * FROM `glpi_plugin_fusioninventory_configs` | 0.000 |  
7 | SHOW COLUMNS FROM `glpi_computers` | 0.000 |  
8 | SHOW COLUMNS FROM `glpi_monitors` | 0.001 |  
9 | SHOW COLUMNS FROM `glpi_softwares` | 0.000 |  
10 | SHOW COLUMNS FROM `glpi_networkequipments` | 0.001 |  
11 | SHOW COLUMNS FROM `glpi_peripherals` | 0.000 |  
12 | SHOW COLUMNS FROM `glpi_printers` | 0.000 |  
13 | SHOW COLUMNS FROM `glpi_cartridgeitems` | 0.000 |  
14 | SELECT * FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
15 | SHOW COLUMNS FROM `glpi_consumableitems` | 0.000 |  
16 | SELECT * FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
17 | SHOW COLUMNS FROM `glpi_phones` | 0.000 |  
18 | SHOW COLUMNS FROM `glpi_racks` | 0.001 |  
19 | SHOW COLUMNS FROM `glpi_enclosures` | 0.000 |  
20 | SHOW COLUMNS FROM `glpi_pdus` | 0.001 |  
21 | SHOW COLUMNS FROM `glpi_tickets` | 0.001 |  
22 | SHOW COLUMNS FROM `glpi_problems` | 0.000 |  
23 | SHOW COLUMNS FROM `glpi_changes` | 0.000 |  
24 | SHOW COLUMNS FROM `glpi_ticketrecurrents` | 0.000 |  
25 | SHOW COLUMNS FROM `glpi_softwarelicenses` | 0.001 |  
26 | SHOW COLUMNS FROM `glpi_budgets` | 0.000 |  
27 | SHOW COLUMNS FROM `glpi_suppliers` | 0.000 |  
28 | SHOW COLUMNS FROM `glpi_contacts` | 0.000 |  
29 | SHOW COLUMNS FROM `glpi_contracts` | 0.001 |  
30 | SELECT * FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
31 | SHOW COLUMNS FROM `glpi_documents` | 0.000 |  
32 | SHOW COLUMNS FROM `glpi_lines` | 0.000 |  
33 | SHOW COLUMNS FROM `glpi_certificates` | 0.000 |  
34 | SHOW COLUMNS FROM `glpi_datacenters` | 0.000 |  
35 | SHOW COLUMNS FROM `glpi_projects` | 0.000 |  
36 | SHOW COLUMNS FROM `glpi_reminders` | 0.000 |  
37 | SHOW COLUMNS FROM `glpi_rssfeeds` | 0.000 |  
38 | SHOW COLUMNS FROM `glpi_knowbaseitems` | 0.000 |  
39 | SHOW COLUMNS FROM `glpi_users` | 0.001 |  
40 | SHOW COLUMNS FROM `glpi_groups` | 0.000 |  
41 | SHOW COLUMNS FROM `glpi_entities` | 0.001 |  
42 | SELECT COUNT(*) AS cpt FROM `glpi_mailcollectors` | 0.000 |  
43 | SHOW COLUMNS FROM `glpi_profiles` | 0.000 |  
44 | SELECT `name` FROM `glpi_profilerights` | 0.001 |  
45 | SHOW COLUMNS FROM `glpi_fieldunicities` | 0.000 |  
46 | SHOW COLUMNS FROM `glpi_mailcollectors` | 0.000 |  
47 | SHOW COLUMNS FROM `glpi_links` | 0.000 |  
48 | SELECT `agent_base_url` FROM `glpi_plugin_fusioninventory_entities` WHERE `entities_id`='0' AND `agent_base_url` IS NOT NULL AND `agent_base_url` != '' LIMIT 1 | 0.000 |  
49 | SELECT `id` FROM `glpi_crontasks` WHERE `glpi_crontasks`.`name` = 'taskscheduler' AND `glpi_crontasks`.`itemtype` = 'PluginFusioninventoryTask' | 0.000 |  
50 | SELECT * FROM `glpi_crontasks` WHERE `glpi_crontasks`.`id` = '33' LIMIT 1 | 0.000 |  
51 | SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%' | 0.001 |  
52 | SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%' | 0.001 |  
53 | SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_db') | 0.000 |  

**taskscheduler is running:**

`MariaDB [glpi]> SELECT * FROM glpi_crontasks WHERE glpi_crontasks.id = '33' LIMIT 1;`
+----+---------------------------+---------------+-----------+-------+-------+------+-----------+---------+---------+---------------+---------------------+----------+---------+---------------------+---------------------+
| id | itemtype                  | name          | frequency | param | state | mode | allowmode | hourmin | hourmax | logs_lifetime | lastrun             | lastcode | comment | date_mod            | date_creation       |
+----+---------------------------+---------------+-----------+-------+-------+------+-----------+---------+---------+---------------+---------------------+----------+---------+---------------------+---------------------+
| 33 | PluginFusioninventoryTask | taskscheduler |       300 |  NULL |     1 |    2 |         3 |       0 |      24 |            30 | 2018-11-02 11:23:00 |     NULL | NULL    | 2018-11-02 10:03:02 | 2018-06-05 16:59:21 |
+----+---------------------------+---------------+-----------+-------+-------+------+-----------+---------+---------+---------------+---------------------+----------+---------+---------------------+---------------------+
1 row in set (0.000 sec)

Any other information required?

**Comment by ddurieux** [comment] 2018-11-02 10:49
Any errors in glpi/files/_logs/php-errors.log ou sql-errors.log ?

**Comment by ppenin** [comment] 2018-11-02 11:18
No error in logs


Le 2 nov. 2018 à 11:49, David Durieux <notifications@github.com<mailto:notifications@github.com>> a écrit :


Any errors in glpi/files/_logs/php-errors.log ou sql-errors.log ?

**Comment by GitStorm** [comment] 2018-11-02 13:08
Just warnings as far as I can see. When I enable debug mode in the UI, I get the following red lines in the top area:

PHP Warning: Declaration of PluginFusioninventoryInventoryRuleLocation::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array) in /var/www/glpi-9.3.2/plugins/fusioninventory/inc/inventoryrulelocation.class.php at line 0
PHP Warning: Declaration of PluginFusioninventoryInventoryRuleEntity::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array) in /var/www/glpi-9.3.2/plugins/fusioninventory/inc/inventoryruleentity.class.php at line 0
PHP Warning: Declaration of PluginFusioninventoryInventoryRuleImport::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array) in /var/www/glpi-9.3.2/plugins/fusioninventory/inc/inventoryruleimport.class.php at line 0
PHP Warning: Declaration of PluginFusioninventoryCollectRule::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array) in /var/www/glpi-9.3.2/plugins/fusioninventory/inc/collectrule.class.php at line 0

**/var/www/glpi/files/_log/sql_errors.log does not exist**

**/var/www/glpi/files/_log/php_errors.log:**
2018-11-02 14:00:00 [6@GlpiServerFqdn]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:440                          Toolbox::deprecated()
  inc/db.function.php:238                            DbUtils->getAllDataFromTable()
  ...usioninventory/inc/formatconvert.class.php:1758 getAllDatasFromTable()
  ...ry/inc/inventorycomputerinventory.class.php:475 PluginFusioninventoryFormatconvert->extraCollectInfo()
  ...inventory/inc/inventoryruleimport.class.php:769 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1464                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
2018-11-02 14:00:00 [6@GlpiServerFqdn]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:440                          Toolbox::deprecated()
  inc/db.function.php:238                            DbUtils->getAllDataFromTable()
  ...usioninventory/inc/formatconvert.class.php:1773 getAllDatasFromTable()
  ...ry/inc/inventorycomputerinventory.class.php:475 PluginFusioninventoryFormatconvert->extraCollectInfo()
  ...inventory/inc/inventoryruleimport.class.php:769 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1464                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
2018-11-02 14:00:00 [6@GlpiServerFqdn]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:440                          Toolbox::deprecated()
  inc/db.function.php:238                            DbUtils->getAllDataFromTable()
  ...usioninventory/inc/formatconvert.class.php:1788 getAllDatasFromTable()
  ...ry/inc/inventorycomputerinventory.class.php:475 PluginFusioninventoryFormatconvert->extraCollectInfo()
  ...inventory/inc/inventoryruleimport.class.php:769 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1464                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
2018-11-02 14:00:00 [6@GlpiServerFqdn]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:323                          Toolbox::deprecated()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  ...ventory/inc/inventorycomputerlib.class.php:1577 countElementsInTable()
  ...nventory/inc/inventorycomputerlib.class.php:985 PluginFusioninventoryInventoryComputerLib->manageNetworkPort()
  ...ry/inc/inventorycomputerinventory.class.php:538 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:769 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1464                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
2018-11-02 14:02:17 [6@GlpiServerFqdn]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:440                          Toolbox::deprecated()
  inc/db.function.php:238                            DbUtils->getAllDataFromTable()
  plugins/fusioninventory/inc/timeslot.class.php:189 getAllDatasFromTable()
  plugins/fusioninventory/inc/task.class.php:344     PluginFusioninventoryTimeslot->getTimeslotEntries()
  ...fusioninventory/inc/communication.class.php:270 PluginFusioninventoryTask->getTaskjobstatesForAgent()
  ...fusioninventory/inc/communication.class.php:472 PluginFusioninventoryCommunication->getTaskAgent()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()

**Comment by GitStorm** [comment] 2018-11-02 13:35
MariaDB [glpi]> SHOW CREATE TABLE glpi_plugin_fusioninventory_taskjoblogs;
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                                   | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| glpi_plugin_fusioninventory_taskjoblogs | CREATE TABLE `glpi_plugin_fusioninventory_taskjoblogs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `plugin_fusioninventory_taskjobstates_id` int(11) NOT NULL DEFAULT 0,
  `date` datetime DEFAULT NULL,
  `items_id` int(11) NOT NULL DEFAULT 0,
  `itemtype` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `state` int(11) NOT NULL DEFAULT 0,
  `comment` text COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `plugin_fusioninventory_taskjobstates_id` (`plugin_fusioninventory_taskjobstates_id`,`state`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+-----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

**Comment by Megachip** [comment] 2018-11-02 13:42
I've 88030 rows in set (0.17 sec), but it displays none. But logs on different tasks working fine.

GPLI 9.2.4 FI 9.2+2.0.

No related logs in SQL or PHP errors.

**Comment by ddurieux** [comment] 2018-11-02 13:49
I'm really lost, and not sure we have same problem here.
is the problem in this issue:
* not data in `glpi_plugin_fusioninventory_taskjoblogs` ?
* data in `glpi_plugin_fusioninventory_taskjoblogs` but display nothing in the plugin (page monitoring log) ?

**Comment by ppenin** [comment] 2018-11-02 13:50
Hello,

Fo me :

  *   data in glpi_plugin_fusioninventory_taskjoblogs but display nothing in the plugin (page monitoring log)


Cordialement,

Patrice PENIN
Directeur des systèmes d’information
Direction Générale - Mulhouse
ppenin@groupesaintsauveur.fr<mailto:ppenin@groupesaintsauveur.fr> - 06 74 93 33 92

Groupe Saint Sauveur
Santé Enfance Handicap Senior

Découvrez le GCSMS Partenariat et Développement en cliquant ici.<http://www.groupesaintsauveur.fr/qui-sommes-nous/gcsms>

Pensez à l’environnement. Avez-vous besoin d'imprimer ce courriel ?
Ce message et les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels.
Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.


De : David Durieux [mailto:notifications@github.com]
Envoyé : vendredi 2 novembre 2018 14:50
À : fusioninventory/fusioninventory-for-glpi <fusioninventory-for-glpi@noreply.github.com>
Cc : Penin Patrice <ppenin@groupesaintsauveur.fr>; Mention <mention@noreply.github.com>
Objet : Re: [fusioninventory/fusioninventory-for-glpi] 9.2+1.0-9.3+1.1: Display/Usability Issue: "Tasks - Monitoring/Logs" empty (#2600)


I'm really lost, and not sure we have same problem here.
is the problem in this issue:

  *   not data in glpi_plugin_fusioninventory_taskjoblogs ?
  *   data in glpi_plugin_fusioninventory_taskjoblogs but display nothing in the plugin (page monitoring log) ?

**Comment by GitStorm** [comment] 2018-11-02 13:53
In our case: not data in glpi_plugin_fusioninventory_taskjoblogs

**Comment by ddurieux** [comment] 2018-11-02 13:57
Ok, so this issue is bad.
I close it, please recreate one issue for each distinct problem, because we have 2 problems in same issue and I will be crazy :p

Thanks

**Closed by ddurieux** 2018-11-02 13:57 UTC
