### ISSUE TITLE
[GLPI 9.5.2 - FusionInventory 9.5.0+1.0 ]+[Fusion Inventory 2.5.2 windows]: Detection "Scanner USB" with fusioninventory

### ISSUE THREAD

**Issue by steph461** [fusioninventory/fusioninventory-for-glpi#3058] opened 2020-11-09 13:05 UTC
Hello,

I have FI-7030 scanner USB made by FUJITSU

I cannot mount the "FI-7030 (fujitsu)" USB scanners with  FusionInventory and logs  I have no trace
They all have the twain function

I have this problem for a long time (first installation 9.3.x to 9.5.2 and all version fusioninventory)

In the device manager, the scanner is correctly mounted
![image](https://user-images.githubusercontent.com/68054991/98544026-a80ea100-2293-11eb-85a0-d796f0f2eea5.png)
![image](https://user-images.githubusercontent.com/68054991/98544092-bfe62500-2293-11eb-80b5-fd3c217c204d.png)

Do you have an idea of the problem ? Is this a problem specific to the scanner USB ?

I tried in the import rules, I did not succeed

For the moment, I mount my scanners manually

**Comment by steph461** [comment] 2020-11-09 13:25
Description du pilote USB SCANNER 

Driver name fi-7030
Manufacturer FUJITSU
Version 2.0.0.3
Inf file oem64.inf
Image type
USB hardware identifier \ VID_04C5 & PID_151F & REV_0100

Manufacturer name Fujitsu, Ltd (Manufacturer ID: 0x04C5)
USB version supported 2.0
Device version 1.0
Class 0x00
Subclass 0x00
Interface class 0x00
Interface subclass 0x00

**Comment by steph461** [comment] 2020-11-16 18:04
#3061

**Comment by trasher** [comment] 2020-11-17 06:48
closed as duplicate of #3061

**Closed by trasher** 2020-11-17 06:48 UTC
