### ISSUE TITLE
DEVICEID - if is generated in the same way as in OCS Agent should be changed

### ISSUE THREAD

**Issue by mariaczi** [fusioninventory/fusioninventory-for-glpi#2914] opened 2019-12-04 10:49 UTC
Hello.

Could someone tell me how DEVICEID is generated in FusienInventory Agent? If is generated in the same way as in OCS Agent I think that is not the best way. 
I reported the issue with DEVICEID in OCS Agent repo here: https://github.com/OCSInventory-NG/UnixAgent/issues/234

Regards.

**Comment by g-bougard** [comment] 2019-12-04 11:05
Hi @mariaczi 
this is historical as FIA was a fork of OCS Agent years ago, but yes it should be generated the same way.
Looking at your OCS issue, the problem is not the deviceid itself but the way you're are templating your systems.
You should probably complete your template by adding a task that will force to use a new deviceid after the first inventory and where a machine is fully setup,maybe with a new name. This is easy, you just have to remove the `FusionInventory-Agent.dump` file in the "**var**" folder (depends on your system or agent installation process).

**Comment by g-bougard** [comment] 2019-12-04 11:09
Btw you can request a [FusionInventory Agent feature](https://github.com/fusioninventory/fusioniinventory-agent/issues) asking for another to create the deviceid. Maybe "<hostname>"-"<random UUID>" would be a simple alternative and it would be easy to develop.

**Comment by mariaczi** [comment] 2019-12-04 11:15
Sure, I can remove "FusionInventory-Agent.dump" file but when the server is up few days before will be the decision for which will be used I don't know the new hostname for it. In the same time I will be happy to have this server inventoried after provisioning with the hostname from template. It is not obligatory that we must have different hostname on all servers, so... DEVICEID generated based on hostname and time from crontab it is not the best way as I wrote before.
In my opinion DEVICEID should be unique for all inventoried machines and not depends on trivial cases.

**Comment by g-bougard** [comment] 2019-12-04 13:57
I agree this is not the best way, but this is just the deviceid. This will only have the impact of not having the right "agent" linked to your computer. This is not really a big deal unless you have specific FusionInventory task to run from a given agent. In your case, if this concern a lot of agent, you'll have a wrong agent count and this can make troubleshooting difficult on some problems.

I can give you another simple advice for your crontab start: use the "-w" option as this will delay the agent first run with a random delay. This will also affect the deviceid created. Don't hesitate to put a large delay if you have a lot of agent template starting at the same time to minimize the risk of deviceid collision.

Finally, I'm closing the issue as we proposed alternatives. Open another one in the right repo to request a feature if you really need such feature.

**Closed by g-bougard** 2019-12-04 13:57 UTC

**Comment by mariaczi** [comment] 2019-12-04 14:08
Using "-w" it is only workaround not the solution to the real situation. I exactly know, it is yours software but with this issue it is not possible to use with massive server provisioning from template, so... thanks for yours answers and time ;)
I think that the user shouldn't thinking about if can use or not the same hostname, because using the same hostname can have impact on inventory process.
Regards.

**Comment by g-bougard** [comment] 2019-12-04 14:34
I agree, this is just a workaround. But if you need a solution for massive server provisioning, you should definitively ask for professional support. Does your company have a [GLPI Subscription](https://glpi-project.org/subscriptions/) ?
We can also provide a safe and short script to help you set the deviceid to follow your needs.

**Comment by mariaczi** [comment] 2019-12-10 14:39
Sorry, we use OCS. I'm wrote here to inform you and others about this inconvenience.
